name: test
env:
  version_type: ""
on:
  push:
    branches:
      - master

jobs:
  getVersionBumpType:
    runs-on: ubuntu-latest
    steps:
    - uses: rluvaton/get-strongest-label-in-pr-action@master
      id: stongestLabel
      with:
        major: "bump:major"
        minor: "bump:minor"
        patch: "bump:patch"
    - name: What is the strongest label in the 'pull_request':+ ${steps.checkLabel.outputs.strongestLabelText} which is ${steps.checkLabel.outputs.strongestLabel}
      run: echo "${{ steps.stongestLabel.outputs.strongestLabel }}" 
    - name: Set Output as env variable
      run: echo "::set-env name=version_type::${{ steps.stongestLabel.outputs.strongestLabel }}"
  
  check_right_version_type:
    needs: [getVersionBumpType]
    runs-on: ubuntu-latest
    steps:
      - id: check
        run: echo {{env.version_type}}
  
#   build:
#     needs: getVersionBumpType
#     runs-on: ubuntu-latest
#     steps:
#     - uses: Dreamcodeio/pr-has-label-action@master
#       id: checkLabel
#       with:
#         label: bump:patch
#     - name: Does 'pull_request' has 'bump:major' label? 
#       run: "npm version"
#       if: steps.checkLabel.outputs.hasLabel
