name: test
env:
  version_type: ""
on:
  push:
    branches:
      - master

jobs:
  getVersionBumpType:
    runs-on: ubuntu-latest
    steps:
     - uses: rluvaton/get-strongest-label-in-pr-action@master
       id: strongestLabel
       with:
        GitHubToken: ${{ secrets.MY_GITHUB_TOKEN }}
        labels: "[[\"bump:major\", \"major\"],[\"bump:minor\", \"minor\"],[\"bump:patch\", \"patch\"],]"

     - name: Echo Label if it's merged pull request commit
       if: steps.strongestLabel.outputs.error != 'no pull request'
       run: echo ${{steps.strongestLabel.outputs.strongestLabelValue}} 
  
#   build:
#     needs: getVersionBumpType
#     runs-on: ubuntu-latest
#     steps:
#     - uses: Dreamcodeio/pr-has-label-action@master
#       id: checkLabel
#       with:
#         label: bump:patch
#     - name: Does 'pull_request' has 'bump:major' label? 
#       run: "npm version"
#       if: steps.checkLabel.outputs.hasLabel
