name: Update Version
on:
  push:
    branches:
      - master

jobs:
  updateAndPublish:
    runs-on: ubuntu-latest
    steps:
     - uses: rluvaton/get-strongest-label-in-pr-action@v4.0.0
       id: strongestLabel
       with:
        GitHubToken: ${{ secrets.GITHUB_TOKEN }}
        labels: "[[\"bump:major\", \"major\"],[\"bump:minor\", \"minor\"],[\"bump:patch\", \"patch\"]]"

     - name: Increase Version
       if: steps.strongestLabel.outputs.error == 0 # No Error
       run: npm version ${{steps.strongestLabel.outputs.strongestLabelValue}}

