name: Update Version
on:
  push:
    branches:
      - master

jobs:
  updateAndPublish:
    runs-on: ubuntu-latest
    steps:
     - uses: rluvaton/get-strongest-label-in-pr-action@v4.0.0
       id: strongestLabel
       with:
        GitHubToken: ${{ secrets.GITHUB_TOKEN }}
        labels: "[[\"bump:major\", \"major\"],[\"bump:minor\", \"minor\"],[\"bump:patch\", \"patch\"]]"

     - name: Fail Job if prev step failed or have error
       if: failure() || steps.strongestLabel.outputs.error != 0
       run: exit 1
     
     - uses: actions/checkout@v2
     - name: NPM Install 
       run: sudo npm install
     - name: Set Git config
       if: success()
       run: |
         git config user.email "rluvaton@gmail.com"
         git config user.name "Raz Luvaton"
     - name: Increase Version
       if: success()
       run: npm version ${{steps.strongestLabel.outputs.strongestLabelValue}}

